@startuml
skinparam dpi 300
skinparam shadowing false

actor Usuário
participant "Módulo botão de pânico"
participant "Tela principal"

Usuário -> "Módulo botão de pânico" : Botão pressionado 
activate "Módulo botão de pânico"
"Módulo botão de pânico" -> "Módulo botão de pânico" : Mensagens enviada\npara contatos 

"Módulo botão de pânico" -> "Tela principal" : Mensagem apresentada\npara usuário final 
activate "Tela principal"

Usuário -> "Módulo botão de pânico" : Fechar mensagem
deactivate "Módulo botão de pânico"
deactivate "Tela principal"

@enduml
