@startuml
skinparam dpi 300
skinparam shadowing false

actor Usuário 
actor Sistema

Usuário -> (pressionar botão\nde pânico)

Sistema -> (detectar botão de pânico\npressionado)
Sistema --> (enviar mensagens\npara contatos)

@enduml
