@startuml
skinparam dpi 300
skinparam shadowing false

!define Table(name,desc) class name as "desc" << (T,#FFFFCC) >>
' we use bold for primary key
' green color for unique
' and underscore for not_null
!define primary_key(x) <b>x</b>
!define unique(x) <color:green>x</color>
!define not_null(x) <u>x</u>
' other tags available:
' <i></i>
' <back:COLOR></color>, where color is a color name or html color code
' (#FFAACC)
' see: http://plantuml.com/classes.html#More
hide circle
hide methods
hide stereotypes
' entities

Table(usuarios, "usuarios") {
primary_key(id) INTEGER
not_null(unique(stb_id)) VARCHAR[32]
not_null(nome) VARCHAR[64]
}

Table(contatos, "contatos") {
primary_key(id) INTEGER
not_null(usuarios_id) INTEGER
not_null(nome) VARCHAR[64]
not_null(unique(email) VARCHAR[64]
not_null(unique(telefone) VARCHAR[64]
}

Table(alertas, "alertas") {
primary_key(id) INTEGER
not_null(usuarios_id) INTEGER
not_null(titulo) VARCHAR[64]
not_null(mensagem) VARCHAR[64]
not_null(tipo) INTEGER 
not_null(data_inicio) VARCHAR[64]
not_null(data_termino) VARCHAR[64]
}

' relationships
' one-to-one relationship
' user -- user_profile : "A user only \nhas one profile"
' one to may relationship
usuarios "1" --> "*" contatos 
usuarios "1" --> "*" alertas 
@enduml
